### ISSUE TITLE
Neither "secure backup" nor "E2E room keys" are sufficient to decrypt all messages

### ISSUE THREAD

**Issue by aerusso** [vector-im/element-meta#1883] opened 2023-07-14 20:48 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
- I have a room between two users on a synapse server.  The messages in that room are all visible on one element session.
- I add a new element session (happens to be on android, if that matters).
- I use the secure passphrase to restore all keys.  This does not let me see all the messages.
- I export all room keys from the element web session.
- I import these into the android client.  I can see more messages, but I still do not see all messages.

### Outcome
I cannot see all messages.

#### What did you expect?
I should be able to see all messages.

#### What happened instead?
I cannot see all messages.

### Operating system
Linux (Debian unstable) and Android (Moto x4 Lineageos)

### Application version

1.11.35, self-hosted web and F-droid

### How did you install the app?

f-droid

### Homeserver

synapse 1.87.0, on Debian bookworm server

### Will you send logs?

Yes

**Comment by richvdh** [comment] 2023-11-07 12:00
There is no insight here into what is special about the messages that cannot be decrypted. Closing as a duplicate of #245

**Closed as completed by richvdh** 2023-11-07 12:00 UTC
Labels: T-Defect
