### ISSUE TITLE
Inconsistent room creation behavior for history visibility

### ISSUE THREAD

**Issue by gabrc52** [vector-im/element-meta#1999] opened 2023-08-22 06:24 UTC
When creating private rooms outside of a space, Element Web, Element Android and Element iOS set history visibility to `shared`.

When creating non-public rooms inside a space, Element Android an Element iOS set history visibility to `shared`, however Element Web sets it to `invite`. 

In my opinion, Element Android and Element iOS have the best behavior, since I believe if someone creates a room in a space and makes it visible from space members, and the space is already public, the most sensible option is to share all the history, like most rooms on matrix.org.

**Comment by richvdh** [comment] 2023-08-22 13:26
This is closely related to https://github.com/matrix-org/matrix-spec/issues/633, which notes that there is no clear definition of "private room".

Seems to be a duplicate of https://github.com/vector-im/element-meta/issues/377

**Closed as completed by richvdh** 2023-08-22 13:26 UTC
