### ISSUE TITLE
Photo bundle

### ISSUE THREAD

**Issue by waclaw66** [vector-im/element-meta#2171] opened 2023-11-03 13:42 UTC
#### What would you like to do?
Have a possibility to see photos shared via single share action together in a bundle in the same way as Singnal does.

|Signal|Element X|
|-|-|
|![Screenshot_20231103_143544_Signal](https://github.com/vector-im/element-meta/assets/15554561/8991be42-955a-4457-a6c6-72a1529ca3ab)|![Screenshot_20231103_143845_Element X](https://github.com/vector-im/element-meta/assets/15554561/bbbc9515-9ab8-4253-879b-51d1cbeb112f)|

#### Why would you like to do it?
When you share multiple photos, they are shown vertically in the timeline, that is kind of mess, especialy when the amount is higher.

#### How would you like to achieve it?
You decide.

**Comment by t3chguy** [comment] 2023-11-08 15:48
Duplicate of https://github.com/vector-im/element-meta/discussions/754

**Closed as completed by t3chguy** 2023-11-08 15:48 UTC
Labels: T-Enhancement
