### ISSUE TITLE
Allow not automatically subscribing to unread notifications for every thread

### ISSUE THREAD

**Issue by Standard8** [vector-im/element-meta#1398] opened 2023-04-05 07:20 UTC
#### What would you like to do?

I would like to be able to *not* receive unread notifications for every new thread, but only the ones I am actually interested in - or maybe not get notified about them after the first time I'm notified about the new thread.

#### Why would you like to do it?

In the rooms I subscribe to, many of the conversations aren't directly relevant to me. Some of them are or are of interest, which is why I follow the rooms.

The problem with threads currently, is that even if I haven't viewed the thread, I get subscribed to unread notifications (unless this is a bug, but I don't see one on file).

Hence, if someone starts or continues a thread on something that I don't care about, then I get notified about it, and I have to go through the process of visiting the room, figuring out there's a new thread, opening the pane, going back from the previous thread I had open, then seeing what the new threads were and finding out I wasn't interested in them, but I'm still going to get notifications for them.

That's a lot of work for threads that I'm simply not interested in. Whilst I could simply mark the room as read, I'd still have to get to the thread view before I know if there's anything relevant or not.

#### How would you like to achieve it?

I think there needs to be some sort of option or change so that we're not automatically subscribed to threads for unread notifications.

Maybe the UI could be changed so that new threads are mentioned at the bottom of the main chat display so that you know when they start, but you don't have to subscribe to them.

Being able to unsubscribe from a thread would also be useful (sometimes you start watching or get notified about it, but aren't actually interested in it). I guess then you also need to be able to subscribe somehow.

### Have you considered any alternatives?

I'm open to alternatives, but I'm not a UX person. This is mainly to start a discussion about the problems I have with threads.

**Comment by clokep** [comment] 2023-04-05 11:57
Duplicate of #984, I believe.

**Closed as completed by clokep** 2023-04-05 11:57 UTC
Labels: T-Enhancement
