### ISSUE TITLE
Video Rooms on Mobile

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#269] opened 2022-05-12 09:05 UTC
**Describe the bug**
When a Video Room (in Beta) receives a message I get a notification on my Mobile device. The push notification, when I click it, takes me to a blank screen... When I press back I go to my room list and the room is not there at all (so I cannot read the notification) 

We need a much better fallback solution for Video Rooms _before_ we release Video Rooms to Stable-Production in Beta.

Ideas for handling this:
- Don't send push notifications on mobile for video rooms
- Act the same way as rooms with a jitsi plugin 
- Show the room as a regular room 
- Show an error message

**Comment by daniellekirkwood** [comment] 2022-05-12 09:05
@frakic @novocaine @nadonomy @robintown 

Let me know if you'd like more info.

**Comment by robintown** [comment] 2022-05-12 12:11
I can't reproduce this on Android:

https://user-images.githubusercontent.com/48614497/168071756-cb21cfaa-68f0-464f-b74a-46de91d22527.mp4

The room also appears as normal in the room list. Is this an iOS-specific bug then?

**Comment by daniellekirkwood** [comment] 2022-05-12 13:13
Let me test on Android and get back to you - but yes, I'm mostly an iOS user

**Comment by robintown** [comment] 2022-05-12 14:45
Transferring to the iOS repo since I've remembered that iOS does filter out all room types that it doesn't recognize, and I pretty confidently recall that this behavior is specific to that client

**Comment by robintown** [comment] 2022-05-12 14:45
Actually, I don't have permission to transfer, so will close this and reopen there

**Closed as completed by robintown** 2022-05-12 14:45 UTC
Labels: T-Defect
