### ISSUE TITLE
Allow to filter threads on unreads

### ISSUE THREAD

**Issue by JurgenG** [vector-im/element-meta#2209] opened 2023-11-20 09:20 UTC
#### What would you like to do?
* only show threads with unread elements

#### Why would you like to do it?
* currently it is very hard to find (older) unread threads, or confirm that there actually are no unread messages in threads

#### How would you like to achieve it?
Add an item to the pulldown menu on threads (see mockup below)
![image](https://github.com/vector-im/element-web/assets/691954/4737656f-cf88-4f85-a3ed-fa99911155dc)

### Have you considered any alternatives?

Yes, and have discussed with multiple people - who expressed this as a major hurdle (together with false unreads) to incorporate Element as a daily tool

### Additional context

Thanks for otherwise a great product!

**Comment by t3chguy** [comment] 2023-11-20 12:20
Duplicate of https://github.com/vector-im/element-meta/discussions/1825

**Closed as completed by t3chguy** 2023-11-20 12:20 UTC
Labels: T-Enhancement
