### ISSUE TITLE
Multiple choices for Polls

### ISSUE THREAD

**Issue by antonengelhardt** [vector-im/element-meta#2319] opened 2024-02-29 15:46 UTC
#### What would you like to do?

Select multiple options for Polls.

#### Why would you like to do it?

Example: For meeting time polls, i would like to be able to select multiple timewindows and not just one.

#### How would you like to achieve it?

By clicking any option and clicking it again to unselect it.

### Have you considered any alternatives?

Doodle

**Comment by antonengelhardt** [comment] 2024-03-01 06:33
@t3chguy Thanks for transferring. Now I see that this is a duplicate of #2295. should we close this issue?

**Comment by t3chguy** [comment] 2024-03-01 09:57
Good spot

**Comment by t3chguy** [comment] 2024-03-01 09:57
Duplicate of #2295

**Closed as not planned by t3chguy** 2024-03-01 09:57 UTC
Labels: T-Enhancement
