### ISSUE TITLE
Crypto | Be helpful to users facing UTDs

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#249] opened 2022-05-02 08:05 UTC
**Be helpful to users facing Unable To Decrypt Erros:**
Give more useful feedback, and provide easily actionable recovery options that actually work.

## App Work

  - \[ \] Implement [UISI feedback screen](https://www.figma.com/file/a1NWmg6mOi2VZuSgaJx6nD/Displaying-UISI?node-id=344%3A14637)
      - \[ \] **Web**
      - \[ \] **Android** \[In Progress\]
      - \[ \] **iOS**
  - \[ \] Update [UISI display in Timeline](https://www.figma.com/file/a1NWmg6mOi2VZuSgaJx6nD/Displaying-UISI?node-id=311%3A14310)
      - \[ \] **Web** https://github.com/vector-im/element-web/issues/20532
      - \[ \] **Android** https://github.com/vector-im/element-android/issues/4940 \[In Progress\]
      - \[ \] **iOS**
  - \[ \] https://github.com/vector-im/element-meta/issues/76
      -   \[ \] EA https://github.com/vector-im/element-android/issues/4891 [Draft PR](https://github.com/vector-im/element-android/pull/5006)
      -  \[ \] EW https://github.com/vector-im/element-web/issues/20454
      - \[ \] **iOS**

**Comment by pmaier1** [comment] 2023-01-20 12:21
FYI - This issue is mostly to take care of UX for known and intentional cases of UTDs after resolving bug-/performance-/reliability-related UTDs.

**Comment by pmaier1** [comment] 2023-08-10 14:33
From a product POV we don't want to expose more crypto-related information to users as we don't think it will be useful. Instead we need to fix the root causes of unexpected UTDs and find smart solutions for expected UTDs (e.g., due to netsplit/outages or when a user puposefully does not have access to keys).

**Closed as completed by pmaier1** 2023-08-10 14:33 UTC
Labels: T-Epic, Team: Crypto
