### ISSUE TITLE
[Story] Leave a room from room-detail view

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1104] opened 2023-03-08 15:32 UTC
As a room-member I want to be able to leave a room from the room-detail page I can get rid of conversations that don't matter to me anymore.

- Show a button to leave the room on the room detail page.
- Show a hint that the user need to confirm that he wants to leave the room

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*
```[tasklist]
### Android
- [x] Implementation
```

- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion

```[tasklist]
### iOS
- [x] Implementation
```

- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion

##  Stretch goals
None at this time

## Out of scope
-

**Comment by amshakal** [comment] 2023-03-27 16:23
Link to figma: 
iOS: https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=1391%3A81439&t=SALHRUFolhzz51OP-1

Android: https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=1452%3A83766&t=SALHRUFolhzz51OP-1

**Comment by manuroe** [comment] 2023-04-11 08:39
@kittykat: iOS is ready for QA

**Comment by jmartinesp** [comment] 2023-04-11 09:05
@kittykat: Android is ready too. This should already be in the nightly build.

**Comment by ghost** [comment] 2023-04-25 17:29
I have been running through some tests on an iPhone 12 mini with iOS 16.3.1 running Element X 1.1.0 (186) and am hitting a crash. I am going to switch over to testing this story on Android now, but I cannot grant QA sign off with this crash on iOS. Please let me know if there is any further information to the following that I can provide.

### Crash 1: Leaving a private room with only one other person
#### Steps
I am starting from a private, encrypted room with only one other person in it.
1. Tap on the room title at the top of the screen
2. Tap on the *Leave room* button at the bottom of the room details screen
3. Tap on the *Leave* button on the warning about needing to be invited back in

#### Expected
I should be removed from the room and taken back to my room list screen.

#### Result
I am presented with a blank page with a back arrow at the top left (see attached screenshot). When I tap the back button the app shows my room list for a brief second and then crashes. I submitted two crash reports so far.

After relaunching the app, if I am invited back in to the room and accept the invite on another device, the room does not show up in my room list in Element X until a restart the app.

### Crash 2: Leaving a public room with many people
#### Steps
I am starting from a public room with many people in it, in this case the Matrix HQ room.
1. Tap on the room title at the top of the screen
2. Tap on the *Leave room* button at the bottom of the room details screen
3. Tap on the *Leave* button on the warning prompt

#### Result
Element X is incorrectly showing only 1 participant (myself) in the Matrix HQ room details view, despite the room having over 40K people in it and me being able to see and participate in the conversation. 

When I try to leave Matrix HQ I am presented with the warning about me leaving a room where I am the only person, probably because of the app incorrectly thinks I am the only person in the room. 

If I leave the room I am presented with the same blank screen as before, tapping back causes the app to crash.

**Comment by Velin92** [comment] 2023-05-11 10:02
> I have been running through some tests on an iPhone 12 mini with iOS 16.3.1 running Element X 1.1.0 (186) and am hitting a crash. I am going to switch over to testing this story on Android now, but I cannot grant QA sign off with this crash on iOS. Please let me know if there is any further information to the following that I can provide.
> 
> ### Crash 1: Leaving a private room with only one other person
> #### Steps
> I am starting from a private, encrypted room with only one other person in it.
> 
> 1. Tap on the room title at the top of the screen
> 2. Tap on the _Leave room_ button at the bottom of the room details screen
> 3. Tap on the _Leave_ button on the warning about needing to be invited back in
> 
> #### Expected
> I should be removed from the room and taken back to my room list screen.
> 
> #### Result
> I am presented with a blank page with a back arrow at the top left (see attached screenshot). When I tap the back button the app shows my room list for a brief second and then crashes. I submitted two crash reports so far.
> 
> After relaunching the app, if I am invited back in to the room and accept the invite on another device, the room does not show up in my room list in Element X until a restart the app.
> 
> ### Crash 2: Leaving a public room with many people
> #### Steps
> I am starting from a public room with many people in it, in this case the Matrix HQ room.
> 
> 1. Tap on the room title at the top of the screen
> 2. Tap on the _Leave room_ button at the bottom of the room details screen
> 3. Tap on the _Leave_ button on the warning prompt
> 
> #### Result
> Element X is incorrectly showing only 1 participant (myself) in the Matrix HQ room details view, despite the room having over 40K people in it and me being able to see and participate in the conversation.
> 
> When I try to leave Matrix HQ I am presented with the warning about me leaving a room where I am the only person, probably because of the app incorrectly thinks I am the only person in the room.
> 
> If I leave the room I am presented with the same blank screen as before, tapping back causes the app to crash.

@ashughes1 

Hi Anthony there were some bug fixes and changes made recently for the room details count and the leave room since it's also being implemented the context menu inside the room.

I performed a test on the current nightly build, and the leave room seems to work fine, can you give it another try?

**Comment by ghost** [comment] 2023-05-25 22:19
@Velin92 I tested this again, using Element X 1.1.1 (224) and the crashes are no longer happening. 

Here is what I am seeing now when I tap on _Leave Room_:
1. The UI shows _Leaving room_ with a spinner for a few seconds before it processes the request
2. I am taken back to the room list as soon as the leave request is completed (no checkmark "Left room" notification is shown: #1703).
3. After leaving the room, it remains in my _All Chats_ list with the room avatar, room title and a message preview. 
4. After a several seconds the message preview changes to _You left the room_.
5. After a few more seconds the room is finally removed from my _All Chats_ list.

**Comment by kittykat** [comment] 2023-06-15 16:36
Signoff passed on Android

@Velin92 is it ready for re-testing on iOS?

**Comment by ghost** [comment] 2023-07-04 11:12
I was retesting this on Element X iOS 1.1.8 (271) and Element X Android Nightly 0.1.0-nightly (1001000) built on July 1, 2023 but unfortunately for Android I am hitting a new issue: https://github.com/vector-im/element-x-android/issues/765. Element X iOS works fine.

Is this reproducible for anyone else? If so, we should try to get this fixed before shipping for public testing. If not, I wouldn't hold the release for it. In either case I am considering QA sign-off work complete for now.

**Comment by jmartinesp** [comment] 2023-07-04 11:31
> Is this reproducible for anyone else? If so, we should try to get this fixed before shipping for public testing. If not, I wouldn't hold the release for it. In either case I am considering QA sign-off work complete for now.

I reproduced it last Friday, but I assumed it was because I was using a very broken account, now I'm not so sure.

**Comment by ghost** [comment] 2023-07-11 12:51
Retested this on Element X iOS 1.2.1 (280) and Element X Android 0.1.0-nightly July 11, 2023. I can confirm that [vector-im/element-x-android#765](https://github.com/vector-im/element-x-android/issues/765) is fixed and I encountered no issues leaving a room from the room details view. Calling this done for QA and good to go to public testing.

**Comment by jmartinesp** [comment] 2023-07-11 13:15
> Retested this on Element X iOS 1.2.1 (280) and Element X Android 0.1.0-nightly July 11, 2023. I can confirm that [vector-im/element-x-android#765](https://github.com/vector-im/element-x-android/issues/765) is fixed and I encountered no issues leaving a room from the room details view. Calling this done for QA and good to go to public testing.

Actually, I'm pretty sure it's still broken. To reproduce you can accept an invite to a room and then try to leave it. This is an [issue in the Rust SDK](https://github.com/matrix-org/matrix-rust-sdk/issues/2078), so both apps should be affected.

**Comment by kittykat** [comment] 2023-07-12 14:22
We have the Rust SDK issue filed, closing this one

**Closed as completed by kittykat** 2023-07-12 14:22 UTC
Labels: App: ElementX Android, App: ElementX iOS, T-User Story, AirFocus - EX Feature - Story, AirFocus - EX Platform - Story, Team: QA, X-Needs-Signoff
