### ISSUE TITLE
Profile biography

### ISSUE THREAD

**Issue by saygo-png** [vector-im/element-meta#1798] opened 2023-06-21 22:51 UTC
### Your use case

I'd like to have a short description under my profile.
It would allow me to give additional context to who I am and link my personal website.
Currently an avatar and username is the only way of sharing information to everyone. This is especially important in big rooms where you will encounter lots of different people.

**Comment by DomMommyXXX** [comment] 2023-06-21 22:55
yes please !!!!!!

**Comment by t3chguy** [comment] 2023-06-22 08:15
Duplicate of https://github.com/vector-im/element-meta/issues/896

**Closed as completed by t3chguy** 2023-06-22 08:15 UTC
Labels: T-Enhancement
