### ISSUE TITLE
Membership Event List Summaries should ignore date separators.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-meta#800] opened 2022-11-01 11:30 UTC
#### What would you like to do?

It's frustrating to go look at an older conversation and see pages upon pages of history looking like:

<img width="669" alt="Screenshot 2022-11-01 at 12 25 52" src="https://user-images.githubusercontent.com/1294269/199222704-9f1caeca-6394-4926-a263-5fca5b917ea4.png">

Currently the MELS (Membership Event List Summary) code honours date separators when collapsing consecutive membership events (i.e. events on different days aren't collapsed together).  Instead, we should just collapse them even if they span multiple days (and then show the date separators again if you expand the MELS).

We'd need to be sure that the right date separator is shown before the MELS however, to show where the sequence began - and perhaps show it at the end too, so the user understands they're being shown a long time range.

#### Why would you like to do it?

To stop you having to scroll through pages of useless membership events to get to the useful content when viewing old conversations.

#### How would you like to achieve it?

Collapse MELS across date boundaries (perhaps with the exception of the most recent date boundary, so the user is clearly shown the daterange being viewed).

### Have you considered any alternatives?

We could also hide profile change events by default - or only show the most recent one for a given user.  However, given we show historical profiles in history, we kinda need the change events too so that users can track which profile is for which user.

### Additional context

This is a nasty papercut, and trivial to fix.

### Are you willing to provide a PR?

Yes

**Comment by kittykat** [comment] 2023-07-26 08:45
Duplicate of #1928

**Closed as not planned by kittykat** 2023-07-26 08:45 UTC
Labels: T-Enhancement, A-Timeline, App: ElementX Android, App: ElementX iOS
