### ISSUE TITLE
Be able to send text with an image

### ISSUE THREAD

**Issue by K4LCIFER** [vector-im/element-meta#1931] opened 2023-07-27 02:20 UTC
#### What would you like to do?

I would like to be able to send text along with an image.

#### Why would you like to do it?

Sometimes it is helpful to give context.

#### How would you like to achieve it?

The way that discord does it is a perfect example. When You add an image, it doesn't immediately send it, but instead adds it above the message box, so that you can add text as regular. When you then send the message, it sends the text first, above the image, and then the image right below all contained within the same message.

### Have you considered any alternatives?

It could be better to send the text after the image, and not necessarily right before the image. I am not convinced of either, at this moment.

**Comment by t3chguy** [comment] 2023-07-27 07:44
Duplicate of https://github.com/vector-im/element-meta/issues/378

**Closed as completed by t3chguy** 2023-07-27 07:44 UTC
Labels: T-Enhancement
