### ISSUE TITLE
E2EE should recover rapidly from HS outages

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-meta#2153] opened 2023-10-19 17:57 UTC
### Your use case

If Bob's HS is down, Alice won't be able to set up Olm sessions to Bob. As a result, her messages to Bob will unavoidably be undecryptable.

Alice's HS could track when Bob's server returns however, and send a push notif to Alice's client when that happens (assuming Alice's client supports push) to encourage Alice to flush her olm/megolm queue and so share the missing key to Bob.

At a minimum Alice's client should track the pending olm sessions that she needs to setup, and keep retrying with a sensible retry schedule in the bg.

**Comment by kegsay** [comment] 2024-01-11 16:24
[MSC4081](https://github.com/matrix-org/matrix-spec-proposals/pull/4081) proposes a way to fix this.

**Comment by richvdh** [comment] 2024-01-12 17:32
closing in favour of #2154

**Closed as completed** 2024-01-12 17:32 UTC
Labels: Team: Crypto, T-Enhancement

**Comment by richvdh** [comment] 2024-01-12 17:41
Duplicate of #2154
